name: MyProgect_01
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
 
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  graphql_flutter: "5.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter # Required for a Flutter project that includes tests
  build_runner: ^2.1.7

flutter:

  uses-material-design: true # Required if you use the Material icon font
